# Generated by Django 2.0.3 on 2018-04-23 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='notice_title',
            new_name='notice',
        ),
    ]
