# Generated by Django 2.0.3 on 2018-04-25 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('noticeboard', '0002_auto_20180423_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_read',
            field=models.BooleanField(default=False, help_text='if checked, notice is read'),
        ),
    ]
