# Generated by Django 2.0.3 on 2018-04-02 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('standards', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('assignment_name', models.CharField(max_length=50)),
                ('standard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standards.Standard')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
