# Generated by Django 2.0.3 on 2018-05-03 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0005_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='time',
            new_name='report_time',
        ),
    ]
