# Generated by Django 2.0.3 on 2018-04-02 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.CharField(blank=True, max_length=255, null=True)),
                ('standard_name', models.CharField(max_length=10)),
                ('standard_identifier', models.IntegerField(unique=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
